version: '3.7'
services:
  web:
    build:
      context: ./rbapi/
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=4 rbapi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/checkgov/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/checkgov/web/static
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: