# Generated by Django 3.2.2 on 2021-06-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.IntegerField(null=True, unique=True)),
                ('bank_name', models.CharField(default=None, max_length=200, null=True)),
                ('support_number_1', models.CharField(default=None, max_length=13, null=True)),
                ('support_number_2', models.CharField(default=None, max_length=13, null=True)),
                ('support_number_3', models.CharField(default=None, max_length=13, null=True)),
                ('email', models.CharField(default=None, max_length=20, null=True)),
                ('website', models.CharField(default=None, max_length=20, null=True)),
                ('info', models.TextField(default=None, max_length=500, null=True)),
                ('signature_info', models.TextField(default=None, max_length=100, null=True)),
                ('signature_person', models.TextField(default=None, max_length=100, null=True)),
                ('sign', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['tax_code', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='RBAResponse',
            fields=[
                ('receipt_id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sender', models.CharField(default=None, max_length=200, null=True)),
                ('recipient', models.CharField(default=None, max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('currencyCode', models.IntegerField(choices=[(980, 'UAH'), (840, 'USD'), (978, 'EUR')], default=None, null=True)),
                ('commissionRate', models.IntegerField(null=True)),
                ('link_code', models.UUIDField(default='bdda734bd5794c07aa56af9604a64ddc', editable=False)),
                ('sender_bank_tax_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender_bank_tax_code', to='api.bankinfo')),
            ],
            options={
                'ordering': ['receipt_id', 'date'],
            },
        ),
    ]
