# Generated by Django 2.2.4 on 2020-02-02 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
