# Generated by Django 3.1.5 on 2021-01-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210131_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='533327c076474fae8cdb4deeb30e0c92', editable=False),
        ),
    ]
