# Generated by Django 2.2.4 on 2020-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rbaresponse_link_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='f269141eae47486d9d184846839e0ab2', editable=False),
        ),
    ]
