# Generated by Django 3.1.5 on 2021-02-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rbaresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbaresponse',
            name='currencyCode',
            field=models.IntegerField(choices=[(980, 'UAH'), (840, 'USD'), (978, 'EUR')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='f2259fa0b18a4e0b8770f1818cbafbe0', editable=False),
        ),
        migrations.AlterField(
            model_name='rbaresponse',
            name='reciept_id',
            field=models.IntegerField(unique=True),
        ),
    ]
