# Generated by Django 3.1.5 on 2021-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210131_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='5e42f865229849a298f892f023c866ab', editable=False),
        ),
    ]
