# Generated by Django 2.2.4 on 2020-03-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200202_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='89c96d1517484345b8a1299e703f822e', editable=False),
        ),
    ]
