# Generated by Django 3.1.5 on 2021-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210213_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbaresponse',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='ae627f9765e342f9aff5e473abbcc911', editable=False),
        ),
    ]
