# Generated by Django 3.1.5 on 2021-02-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210214_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('tax_code', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(default=None, max_length=200, null=True)),
                ('support_number_1', models.CharField(default=None, max_length=13, null=True)),
                ('support_number_2', models.CharField(default=None, max_length=13, null=True)),
                ('support_number_3', models.CharField(default=None, max_length=13, null=True)),
                ('email', models.CharField(default=None, max_length=20, null=True)),
                ('website', models.CharField(default=None, max_length=20, null=True)),
                ('info', models.TextField(default=None, max_length=500, null=True)),
                ('signature_person', models.TextField(default=None, max_length=100, null=True)),
                ('sign', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['tax_code', 'bank_name'],
            },
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.RemoveField(
            model_name='rbaresponse',
            name='id',
        ),
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='ae6fabcd466f4fda94e20d89209a988c', editable=False),
        ),
        migrations.AlterField(
            model_name='rbaresponse',
            name='reciept_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='rbaresponse',
            name='sender_bank_tax_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_bank_tax_code', to='api.bankinfo'),
        ),
    ]
