# Generated by Django 3.1.5 on 2021-02-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210214_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='signature_info',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='1ff85bd218b14118a7f3b80d36ae6ebb', editable=False),
        ),
    ]
