# Generated by Django 3.2.2 on 2021-05-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210224_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbaresponse',
            name='link_code',
            field=models.UUIDField(default='0d0655e9c5944e70861995fa662d13e4', editable=False),
        ),
    ]
